services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env-app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - alga-net
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limita a 50% de uma CPU
          memory: 512M    # Limita a 512MB de mem√≥ria
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    tmpfs:
      - /data:size=256m
    networks:
      - alga-net
    restart: on-failure

networks:
  alga-net:

volumes:
  mysql-data:
